# Generated by Django 4.0.3 on 2022-03-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_like_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='product',
        ),
    ]
